POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Lara",
    "email": "lara@gmail.com",
    "password": "1234ab",
    "confirm_password": "1234ab"
}

PUT http://localhost:3333/users/1